import { Header } from '@/components';
import { UrbanBazaar } from '@/styles';
import '@/styles/globals.css';
import { ThemeProvider } from '@/styles/theme/ThemeProvider';
import type { Metadata } from 'next';
import { ReactNode } from 'react';

const { open_sans } = UrbanBazaar.fonts;

export const metadata: Metadata = {
  title: 'ShopSleek',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <ThemeProvider>
        <body className={`${open_sans.className} bg-bg text-fc`}>
          <Header />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
